### ISSUE TITLE
Build a single app?

### ISSUE THREAD

**Issue by maraisr** [Thinkmill/monorepo-starter#1]
With this setup, is it possible to only build a single app?

**Comment by Noviny** [comment]
I’m not entirely sure what you mean by that. It should be possible to do most things out of this shell, as it’s very minimal.

Can you give me a little more info on what you are trying to achieve?

**Comment by maraisr** [comment]
Ah yeah. Firstly though!! Love this repo... Actually started something very similar a few years ago, before all these fancy tooling came about. But!

What im trying to do is. As this repo has "placeholder-app" say for instance, there was a "app-a" and "app-b" as well. And in my CI, instead of building every app on every push, if there was a way to build just 1 of those apps" Or is that an anti pattern?

On a side note: would also be awesome to also jot down something around CI/CD using this? What a workflow might look like etc..??

**Comment by Noviny** [comment]
> is that an anti pattern?

I guess it's probably a clarity thing here, but by 'build' we really mean 'compile with babel' - which you definitely want to do on the things in `/packages`, and probably want to do on all apps (it's unlikely to be costly). You might have further build steps for your app which you could configure yourself.

> would also be awesome to also jot down something around CI/CD using this?

This would be cool! I think something like this will likely end up in our [style guide](https://github.com/Thinkmill/monorepo) rather than in this project though (which is going through its own rework atm)
